# Generated by Django 4.2.7 on 2023-11-08 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='date_uodated',
            new_name='date_updated',
        ),
    ]
